export enum RobotsActionType {
  REQUEST_ROBOTS_PENDING = "REQUEST_ROBOTS_PENDING",
  REQUEST_ROBOTS_SUCCESS = "REQUEST_ROBOTS_SUCCESS",
  REQUEST_ROBOTS_FAILED = "REQUEST_ROBOTS_FAILED",
}

export enum SearchActionType {
  CHANGE_SEARCHFIELD = "CHANGE_SEARCHFIELD",
}
